# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u9879\u76ee\u540d\u79f0')),
                ('time', models.CharField(max_length=40, verbose_name='\u4e2d\u6807\u65f6\u95f4')),
                ('company', models.CharField(max_length=100, verbose_name='\u4e2d\u6807\u516c\u53f8')),
                ('money', models.CharField(max_length=100, verbose_name='\u4e2d\u6807\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(max_length=100, verbose_name='\u5bc6\u7801')),
                ('email', models.CharField(max_length=20, verbose_name='\u90ae\u7bb1')),
            ],
        ),
    ]
