# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Web',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webAddr', models.CharField(max_length=100)),
            ],
        ),
    ]
